# .github/workflows/deploy.yml
name: Deploy a entornos

on:
  workflow_dispatch

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy a DEV"

  pre:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy a PRE"

  pro:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy a PRO"

  certificacion:           # cuando añadas este job → se crea el environment automáticamente
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy a CERTIFICACION"