name: Reusable Workflow

on:
  workflow_call:
    inputs:
      caller_job:
        type: string
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar quién me llamó
        run: |
          echo "Invocado por: ${{ inputs.caller_job }}"
          echo "Hora: $(date)"