# .github/workflows/reusable.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      caller_job:
        description: 'Nombre del job que me invocó'
        type: string
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar quién me llamó
        run: |
          echo "Fui invocado por: ${{ inputs.caller_job }}"
          echo "Ejecutado en: $(date)"