# .github/workflows/reusable.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      caller_job:
        description: 'Nombre del job que me llamó'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar quién me invocó
        run: |
          echo "Fui llamado por el job: ${{ inputs.caller_job }}"
          echo "Hora actual: $(date)"
          echo "Repositorio: ${{ github.repository }}"